image: Ubuntu2004  # образ для сборки

environment:
  GITHUB_TOKEN:
    secure: rKdsw1KgWV2Z2QuzJ+kmvGT7+WFjazcjsGOZ9hfyf1XRqxp+19cJXCYItRfju89y

stack: node 18  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - ps: Install-Product node $env:nodejs_version
      - corepack enable
      - corepack prepare pnpm@latest-8 --activate
      - pnpm install

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - pnpm lint
  - pnpm build

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - pnpm dlx push-dir --dir=out --branch=gh-pages --force --verbose
